export const TEMPLATES = {
  "double-column": {
    name: "Double Column",
    template: "double-column",
    description: "Clean executive layout",
    region: "europe",
    regionLabel: "Europe",
    regionEmoji: "🇪🇺",
    style: "professional",
    ats: true,
    isNew: true,
    selected: true,
    grid: 2,
    setting: {
      "sections.0.width": 6,
      "sections.1.width": 4,
      gridGap: 30,
    },
    layout: {
      professionalExperience: 0,
      education: 0,
      certifications: 0,
      summary: 1,
      projects: 1,
      skills: 1,
      socialLinks: 1,
    },
  },

  "lvy-league": {
    name: "Lvy League",
    template: "lvy-league",
    description: "Simple and highly readable",
    region: "global",
    regionLabel: "Global",
    regionEmoji: "🌍",
    style: "professional",
    ats: true,
    isNew: false,
    grid: 1,
    setting: {
      "sections.0.width": 1,
    },
    layout: {
      summary: 0,
      skills: 0,
      professionalExperience: 0,
      education: 0,
      certifications: 0,
      projects: 0,
      socialLinks: 0,
    },
  },

  elegant: {
    name: "Elegant",
    template: "elegant",
    description: "Traditional US resume format",
    region: "us",
    regionLabel: "US",
    regionEmoji: "🇺🇸",
    style: "professional",
    ats: true,
    isNew: false,
    grid: 2,
    setting: {
      "sections.0.width": 3,
      "sections.1.width": 7,
      gridGap: 30,
    },
    layout: {
      summary: 0,
      professionalExperience: 0,
      projects: 0,
      socialLinks: 0,
      education: 1,
      skills: 1,
      certifications: 1,
    },
  },

  "creative-edge": {
    name: "Creative Edge",
    template: "creative-edge",
    description: "Modern design for creative roles",
    region: "global",
    regionLabel: "Global",
    regionEmoji: "🌍",
    style: "creative",
    ats: false,
    isNew: true,
    grid: 2,
    setting: {
      "sections.0.width": 1,
      "sections.1.width": 1,
      gridGap: 20,
    },
    layout: {
      professionalExperience: 0,
      skills: 0,
      education: 0,
      socialLinks: 1,
    },
  },

  "euro-modern": {
    name: "Euro Modern",
    template: "euro-modern",
    description: "European-style professional CV",
    region: "europe",
    regionLabel: "Europe",
    regionEmoji: "🇪🇺",
    style: "professional",
    ats: true,
    isNew: false,
    grid: 2,
    setting: {
      "sections.0.width": 6,
      "sections.1.width": 4,
      gridGap: 20,
    },
    layout: {
      professionalExperience: 0,
      skills: 0,
      education: 1,
      socialLinks: 0,
    },
  },
};
