export const TEMPLATES = {
  "executive-pro": {
    name: "Double Column",
    template: "double-column",
    description: "Clean executive layout",
    region: "europe",
    regionLabel: "Europe",
    regionEmoji: "🇪🇺",
    style: "professional",
    ats: true,
    isNew: true,
    selected: true,
    grid: 2,
    setting: {
      "sections.0.width": 7,
      "sections.1.width": 3,
      gridGap: 30,
    },
  },

  minimal: {
    name: "Lvy League",
    template: "lvy-league",
    description: "Simple and highly readable",
    region: "global",
    regionLabel: "Global",
    regionEmoji: "🌍",
    style: "professional",
    ats: true,
    isNew: false,
    grid: 1,
    setting: {
      "sections.0.width": 1,
    },
  },

  american: {
    name: "Elegant",
    template: "elegant",
    description: "Traditional US resume format",
    region: "us",
    regionLabel: "US",
    regionEmoji: "🇺🇸",
    style: "professional",
    ats: true,
    isNew: false,
    grid: 2,
    setting: {
      "sections.0.width": 3,
      "sections.1.width": 7,
      gridGap: 30,
    },
  },

  "creative-edge": {
    name: "Creative Edge",
    description: "Modern design for creative roles",
    region: "global",
    regionLabel: "Global",
    regionEmoji: "🌍",
    style: "creative",
    ats: false,
    isNew: true,
    grid: 2,
    setting: {
      "sections.0.width": 1,
      "sections.1.width": 1,
      gridGap: 20,
    },
  },

  "euro-modern": {
    name: "Euro Modern",
    description: "European-style professional CV",
    region: "europe",
    regionLabel: "Europe",
    regionEmoji: "🇪🇺",
    style: "professional",
    ats: true,
    isNew: false,
    grid: 2,
    setting: {
      "sections.0.width": 6,
      "sections.1.width": 4,
      gridGap: 20,
    },
  },
};
