export const TEMPLATES = {
  "double-column": {
    name: "Double Column",
    template: "double-column",
    description: "Clean executive layout",
    region: "europe",
    regionLabel: "Europe",
    regionEmoji: "🇪🇺",
    style: "professional",
    ats: true,
    isNew: true,
    selected: true,
    grid: 2,
    setting: {
      headerStyle: {
        display: "grid",
        gridTemplateColumns: "auto max-content",
        gap: "30px",
      },
      sectionStyle: {
        display: "grid",
        gridTemplateColumns: "6fr 4fr",
        gap: "30px",
      },
    },
    layout: {
      professionalExperience: 0,
      education: 0,
      certifications: 0,
      summary: 1,
      projects: 1,
      skills: 1,
      socialLinks: 1,
    },
  },

  "lvy-league": {
    name: "Lvy League",
    template: "lvy-league",
    description: "Simple and highly readable",
    region: "global",
    regionLabel: "Global",
    regionEmoji: "🌍",
    style: "professional",
    ats: true,
    isNew: false,
    grid: 1,
    setting: {
      headerStyle: {
        display: "flex",
        flexDirection: "column-reverse",
        gap: "10px",
        alignItems: "center",
        textAlign: "center",
        children: {
          ".contact-info-grid": {
            justifyContent: "center",
          },
        },
      },
      sectionStyle: {
        display: "grid",
        gridTemplateColumns: "1fr",
      },
    },
    layout: {
      summary: 0,
      skills: 0,
      professionalExperience: 0,
      education: 0,
      certifications: 0,
      projects: 0,
      socialLinks: 0,
    },
  },

  elegant: {
    name: "Elegant",
    template: "elegant",
    description: "Traditional US resume format",
    region: "us",
    regionLabel: "US",
    regionEmoji: "🇺🇸",
    style: "professional",
    ats: true,
    isNew: false,
    grid: 2,
    setting: {
      headerStyle: {
        display: "grid",
        gridTemplateColumns: "6fr 4fr",
        gap: "30px",
      },
      sectionStyle: {
        display: "grid",
        gridTemplateColumns: "6fr 4fr",
        gap: "30px",
      },
    },
    layout: {
      summary: 0,
      professionalExperience: 0,
      projects: 0,
      socialLinks: 0,
      education: 1,
      skills: 1,
      certifications: 1,
    },
  },

  "creative-edge": {
    name: "Creative Edge",
    template: "creative-edge",
    description: "Modern design for creative roles",
    region: "global",
    regionLabel: "Global",
    regionEmoji: "🌍",
    style: "creative",
    ats: false,
    isNew: true,
    grid: 2,
    setting: {
      headerStyle: {
        display: "grid",
        gridTemplateColumns: "1fr 1fr",
        gap: "30px",
      },
      sectionStyle: {
        display: "grid",
        gridTemplateColumns: "1fr 1fr",
        gap: "30px",
      },
    },
    layout: {
      professionalExperience: 0,
      skills: 0,
      education: 0,
      socialLinks: 1,
    },
  },

  "euro-modern": {
    name: "Euro Modern",
    template: "euro-modern",
    description: "European-style professional CV",
    region: "europe",
    regionLabel: "Europe",
    regionEmoji: "🇪🇺",
    style: "professional",
    ats: true,
    isNew: false,
    grid: 2,
    setting: {
      headerStyle: {
        display: "grid",
        gridTemplateColumns: "6fr 4fr",
        gap: "30px",
      },
      sectionStyle: {
        display: "grid",
        gridTemplateColumns: "6fr 4fr",
        gap: "30px",
      },
    },
    layout: {
      professionalExperience: 0,
      skills: 0,
      education: 1,
      socialLinks: 0,
    },
  },
};
